"""
Django settings for altixedu project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-04552cmetpb=a+ezspgh(emzc0)pwdga2hkyajzvmilbu=r5@q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts in development
# In production, set to specific hosts only


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',  # ⭐ Token authentication for login
    'django_filters',
    'corsheaders',
    
    # Local apps
    'apps.accounts',
    'apps.schools',
    'apps.students',
    'apps.teachers',  # ⭐ Teacher profiles and management
    'apps.bursars',   # ⭐ Bursar (finance manager) profiles
    'apps.academics',
    'apps.attendance',
    'apps.finance',
    'apps.notifications',
    'apps.billing',  # ⭐ Billing & Subscription Features
    'apps.government',  # ⭐ Government & Compliance Features
    'apps.platform',  # ⭐ Platform-wide features (announcements, AI alerts)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Multi-tenant subdomain routing (must be after auth)
    'altixedu.tenant_middleware.SubdomainTenantMiddleware',
    # Security & Rate Limiting
    'altixedu.middleware.RateLimitingMiddleware',
    'altixedu.middleware.SecurityHeadersMiddleware',
    'altixedu.middleware.AuditLoggingMiddleware',
]

ROOT_URLCONF = 'altixedu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'altixedu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# CACHING CONFIGURATION (for Rate Limiting)
# ============================================================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'altixedu-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 10000
        }
    }
}

# ============================================================================
# RATE LIMITING CONFIGURATION
# ============================================================================
LOGIN_ATTEMPTS_LIMIT = 5  # Max login attempts
LOGIN_ATTEMPTS_WINDOW = 60  # Time window in seconds (1 minute)
API_REQUESTS_LIMIT = 100  # Max API requests per user
API_REQUESTS_WINDOW = 3600  # Time window in seconds (1 hour)

# ============================================================================
# ENCRYPTION CONFIGURATION
# ============================================================================
# Generate encryption key on first run
from cryptography.fernet import Fernet
import os

_ENCRYPTION_KEY_FILE = os.path.join(BASE_DIR, '.encryption_key')
if os.path.exists(_ENCRYPTION_KEY_FILE):
    with open(_ENCRYPTION_KEY_FILE, 'r') as f:
        ENCRYPTION_KEY = f.read().strip()
else:
    # Generate new encryption key for development
    ENCRYPTION_KEY = Fernet.generate_key().decode()
    with open(_ENCRYPTION_KEY_FILE, 'w') as f:
        f.write(ENCRYPTION_KEY)
    os.chmod(_ENCRYPTION_KEY_FILE, 0o600)

# ============================================================================
# AUDIT LOGGING CONFIGURATION
# ============================================================================
AUDIT_LOG_RETENTION_DAYS = 2555  # 7 years per compliance standards
AUDIT_LOG_ENABLED = True  # Set to False to disable audit logging

# ============================================================================
# STRIPE CONFIGURATION (for Billing)
# ============================================================================
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'pk_test_placeholder_for_development')
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'sk_test_placeholder_for_development')

# ============================================================================
# REST FRAMEWORK CONFIGURATION
# ============================================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# ============================================================================
# CORS CONFIGURATION (for Frontend)
# ============================================================================
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',
    'http://localhost:8000',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
]
CORS_ALLOW_CREDENTIALS = True

# ============================================================================
# INTERNATIONALIZATION (i18n) CONFIGURATION
# ============================================================================
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('sw', 'Swahili'),
    ('pt', 'Portuguese'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]
