"""
Django settings for altixedu project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name, default):
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    return [item.strip() for item in raw_value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)  # Default to True for development

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-change-me-before-production'
    else:
        raise ValueError(
            'DJANGO_SECRET_KEY environment variable is required for production. '
            'Generate one using: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
        )

ALLOWED_HOSTS = _env_list(
    'DJANGO_ALLOWED_HOSTS',
    ['localhost', '127.0.0.1', '[::1]', 'testserver'] if DEBUG else ['127.0.0.1', '.altixedu.com']
)


# Application definition

INSTALLED_APPS = [
    'daphne',  # ⭐ ASGI server for WebSocket support
    'channels',  # ⭐ Django Channels for WebSocket support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',  # ⭐ Token authentication for login
    'django_filters',
    'corsheaders',
    
    # Local apps
    'apps.accounts',
    'apps.schools',
    'apps.students',
    'apps.teachers',  # Required for academics.Classroom and TeacherSubject relationships
    'apps.bursars',   # Finance manager profiles
    'apps.academics',
    'apps.attendance',
    'apps.finance',
    'apps.notifications',
    'apps.core',  # ⭐ Core compliance, auditing, and infrastructure
    'apps.billing',  # ⭐ Billing & Subscription Features
    'apps.government',  # ⭐ Government & Compliance Features
    'apps.platform',  # ⭐ Platform-wide features (announcements, AI alerts)
    'apps.analytics',  # ⭐ Advanced Analytics & AI-powered dashboards
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ⭐ Serve static files efficiently
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Multi-tenant subdomain routing (must be after auth)
    'altixedu.tenant_middleware.SubdomainTenantMiddleware',
    # Security & Rate Limiting
    'altixedu.middleware.RateLimitingMiddleware',
    'altixedu.middleware.SecurityHeadersMiddleware',
    'altixedu.middleware.AuditLoggingMiddleware',
]

ROOT_URLCONF = 'altixedu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'altixedu.wsgi.application'

# ============================================================================
# ASGI CONFIGURATION (for WebSocket support)
# ============================================================================
ASGI_APPLICATION = 'altixedu.asgi.application'

# Django Channels configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DJANGO_DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DJANGO_DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': os.getenv('DJANGO_DB_USER', ''),
        'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', ''),
        'HOST': os.getenv('DJANGO_DB_HOST', ''),
        'PORT': os.getenv('DJANGO_DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.getenv('DJANGO_LANGUAGE_CODE', 'en-us')

TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files configuration
STATIC_URL = os.getenv('DJANGO_STATIC_URL', '/static/')
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # ⭐ WhiteNoise compression

# Media files
MEDIA_URL = os.getenv('DJANGO_MEDIA_URL', '/media/')
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# CACHING CONFIGURATION (for Rate Limiting)
# ============================================================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'altixedu-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 10000
        }
    }
}

# ============================================================================
# RATE LIMITING CONFIGURATION
# ============================================================================
LOGIN_ATTEMPTS_LIMIT = 5  # Max login attempts
LOGIN_ATTEMPTS_WINDOW = 60  # Time window in seconds (1 minute)
API_REQUESTS_LIMIT = 100  # Max API requests per user
API_REQUESTS_WINDOW = 3600  # Time window in seconds (1 hour)

# ============================================================================
# ENCRYPTION CONFIGURATION
# ============================================================================
# Generate encryption key on first run for local development
from cryptography.fernet import Fernet

_ENCRYPTION_KEY_FILE = os.path.join(BASE_DIR, '.encryption_key')
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY')
if ENCRYPTION_KEY:
    pass
elif os.path.exists(_ENCRYPTION_KEY_FILE):
    with open(_ENCRYPTION_KEY_FILE, 'r') as f:
        ENCRYPTION_KEY = f.read().strip()
elif DEBUG:
    # Generate new encryption key for development
    ENCRYPTION_KEY = Fernet.generate_key().decode()
    with open(_ENCRYPTION_KEY_FILE, 'w') as f:
        f.write(ENCRYPTION_KEY)
    os.chmod(_ENCRYPTION_KEY_FILE, 0o600)
else:
    raise RuntimeError(
        'ENCRYPTION_KEY must be set when DJANGO_DEBUG is false.'
    )

# ============================================================================
# AUDIT LOGGING CONFIGURATION
# ============================================================================
AUDIT_LOG_RETENTION_DAYS = 2555  # 7 years per compliance standards
AUDIT_LOG_ENABLED = True  # Set to False to disable audit logging

# ============================================================================
# FLUTTERWAVE CONFIGURATION (for Billing)
# ============================================================================
FLUTTERWAVE_BASE_URL = os.getenv(
    'FLUTTERWAVE_BASE_URL',
    'https://api.flutterwave.com/v3'
)
FLUTTERWAVE_SECRET_KEY = os.getenv('FLUTTERWAVE_SECRET_KEY', '')
FLUTTERWAVE_PUBLIC_KEY = os.getenv('FLUTTERWAVE_PUBLIC_KEY', '')
FLUTTERWAVE_SECRET_HASH = os.getenv('FLUTTERWAVE_SECRET_HASH', '')
FRONTEND_APP_URL = os.getenv('FRONTEND_APP_URL', 'http://127.0.0.1:3000')

# ============================================================================
# REST FRAMEWORK CONFIGURATION
# ============================================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# ============================================================================
# CORS CONFIGURATION (for Frontend)
# ============================================================================
CORS_ALLOWED_ORIGINS = _env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    [
        'http://localhost:3000',
        'http://localhost:3001',
        'http://localhost:5173',
        'http://localhost:4173',
        'http://localhost:8000',
        'http://127.0.0.1:3000',
        'http://127.0.0.1:3001',
        'http://127.0.0.1:5173',
        'http://127.0.0.1:4173',
    ] if DEBUG else []
)
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = _env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    CORS_ALLOWED_ORIGINS
)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = _env_bool('DJANGO_USE_X_FORWARDED_HOST', not DEBUG)
SESSION_COOKIE_SECURE = _env_bool('DJANGO_SECURE_COOKIES', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('DJANGO_SECURE_COOKIES', not DEBUG)
SECURE_SSL_REDIRECT = _env_bool(
    'DJANGO_SECURE_SSL_REDIRECT',
    False if DEBUG else True
)

# ============================================================================
# INTERNATIONALIZATION (i18n) CONFIGURATION
# ============================================================================
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('sw', 'Swahili'),
    ('pt', 'Portuguese'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]
