# Generated by Django 5.2.12 on 2026-04-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teacher',
            new_name='teachers_te_school__65785e_idx',
            old_name='teacher_school_status_idx',
        ),
        migrations.RenameIndex(
            model_name='teacher',
            new_name='teachers_te_user_id_d97704_idx',
            old_name='teacher_user_idx',
        ),
    ]
