# Generated by Django 5.2.12 on 2026-05-05 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schools', '0009_school_academic_year_format_school_currency_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Configuration key (e.g., 'MAINTENANCE_MODE')", max_length=100, unique=True)),
                ('value', models.TextField(help_text='Configuration value (JSON for complex types)')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('list', 'List')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this setting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='ISO 4217 currency code (KES, UGX, NGN, etc.)', max_length=3, unique_for_date='date')),
                ('currency_name', models.CharField(help_text='Currency name (e.g., Kenyan Shilling)', max_length=100)),
                ('rate', models.FloatField(help_text='Exchange rate: 1 USD = ? (currency_code)')),
                ('inverse_rate', models.FloatField(help_text='Inverse rate: 1 (currency_code) = ? USD')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date this rate was recorded')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('api', 'API (exchangerate-api.com)'), ('fixer', 'Fixer.io API'), ('other', 'Other Source')], default='api', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Use this rate in conversions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'currency_code'],
                'indexes': [models.Index(fields=['currency_code', '-date'], name='core_curren_currenc_0d5a03_idx'), models.Index(fields=['is_active', '-date'], name='core_curren_is_acti_e18792_idx')],
                'unique_together': {('currency_code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object that was changed')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('soft_delete', 'Soft Deleted'), ('restore', 'Restored'), ('export', 'Exported'), ('import', 'Imported'), ('payment', 'Payment Recorded'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Other')], help_text='Type of action performed', max_length=20)),
                ('description', models.TextField(help_text='Human-readable description of the change')),
                ('changes', models.JSONField(default=dict, help_text='Dictionary of {field: [old_value, new_value]} for updates')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who made the change', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from browser/client')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the change was made')),
                ('content_type', models.ForeignKey(help_text='Django content type of the affected model', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['school', '-timestamp'], name='core_auditl_school__1e2552_idx'), models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'), models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx'), models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfflineAttendanceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.CharField(help_text='UUID for idempotency (prevent duplicate syncs)', max_length=36, unique=True)),
                ('records', models.JSONField(help_text='Array of {date, classroom_id, attendance_data} records')),
                ('num_records', models.IntegerField(help_text='Number of attendance records in this sync')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Failed')], default='pending', max_length=20)),
                ('synced_count', models.IntegerField(default=0, help_text='Number of records successfully synced')),
                ('error_count', models.IntegerField(default=0, help_text='Number of records that failed')),
                ('error_details', models.JSONField(default=list, help_text='Array of {record_index, error_message} for failed records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='When this sync was processed', null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_attendance_syncs', to='schools.school')),
                ('user', models.ForeignKey(help_text='Teacher who marked attendance offline', on_delete=django.db.models.deletion.CASCADE, related_name='offline_attendance_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', '-created_at'], name='core_offlin_school__40c55a_idx'), models.Index(fields=['user', 'status'], name='core_offlin_user_id_4a063a_idx'), models.Index(fields=['sync_uuid'], name='core_offlin_sync_uu_87b9d6_idx')],
            },
        ),
    ]
