# Generated by Django 5.2.12 on 2026-04-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursars', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bursar',
            new_name='bursars_bur_school__892fa9_idx',
            old_name='bursar_school_idx',
        ),
        migrations.RenameIndex(
            model_name='bursar',
            new_name='bursars_bur_user_id_4b5b0e_idx',
            old_name='bursar_user_idx',
        ),
    ]
