# Generated by Django 5.2.12 on 2026-04-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
        ('students', '0006_remove_parent_parent_school_user_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='airiskalert',
            new_name='platform_ai_school__13c8a9_idx',
            old_name='air_school_student_idx',
        ),
        migrations.RenameIndex(
            model_name='airiskalert',
            new_name='platform_ai_school__95e106_idx',
            old_name='air_school_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='platform_an_school__c8e41c_idx',
            old_name='ann_school_created_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='platform_an_school__9d5476_idx',
            old_name='ann_school_role_idx',
        ),
        migrations.AlterField(
            model_name='airiskalert',
            name='alert_type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('grades', 'Grades/Performance'), ('assignment', 'Assignment/Homework'), ('behavior', 'Behavior'), ('health', 'Health'), ('other', 'Other')], help_text='Type of risk detected', max_length=20),
        ),
        migrations.AlterField(
            model_name='airiskalert',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Mark alert as resolved'),
        ),
        migrations.AlterField(
            model_name='airiskalert',
            name='message',
            field=models.TextField(help_text='Alert message with details'),
        ),
        migrations.AlterField(
            model_name='airiskalert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Alert severity level', max_length=20),
        ),
        migrations.AlterField(
            model_name='airiskalert',
            name='student',
            field=models.ForeignKey(blank=True, help_text='NULL means school-wide alert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='students.student'),
        ),
    ]
