# Generated by Django 5.2.12 on 2026-04-28 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_management_models'),
        ('schools', '0007_alter_ministry_options_alter_ministry_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='parentstudentlink',
            new_name='accounts_pa_parent__d3ddc0_idx',
            old_name='accounts_pa_parent__5772df_idx',
        ),
        migrations.RenameIndex(
            model_name='parentstudentlink',
            new_name='accounts_pa_student_633b8a_idx',
            old_name='accounts_pa_student_448ac9_idx',
        ),
        migrations.RenameIndex(
            model_name='studentclassroomassignment',
            new_name='accounts_st_classro_66ecf0_idx',
            old_name='accounts_st_classro_b1de85_idx',
        ),
        migrations.RenameIndex(
            model_name='studentclassroomassignment',
            new_name='accounts_st_student_5c6478_idx',
            old_name='accounts_st_student_655f6e_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'School Admin / Principal'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('bursar', 'School Bursar / Finance Officer'), ('ministry_admin', 'Ministry Admin'), ('superadmin', 'Super Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='NULL for superadmin/ministry_admin, required for other roles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='schools.school'),
        ),
    ]
