# Generated by Django 5.2.12 on 2026-03-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='history',
            field=models.JSONField(default=list, help_text='Payment history with amounts, timestamps, and who recorded'),
        ),
    ]
