# Generated by Django 5.2.12 on 2026-05-05 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_studentfee_history'),
        ('schools', '0008_school_deleted_at_and_more'),
        ('students', '0007_remove_student_parents_delete_studentparent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Unique receipt identifier', max_length=50, unique=True)),
                ('amount', models.FloatField(help_text='Amount paid')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('transfer', 'Bank Transfer'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], default='cash', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(blank=True, help_text='PDF receipt file', null=True, upload_to='payment_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts_issued', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='students.student')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.studentfee')),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['receipt_number'], name='finance_pay_receipt_e7f89d_idx'), models.Index(fields=['student', 'payment_date'], name='finance_pay_student_eef3d3_idx')],
            },
        ),
    ]
