# Generated by Django 5.2.12 on 2026-05-05 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_paymentreceipt'),
        ('schools', '0009_school_academic_year_format_school_currency_code_and_more'),
        ('students', '0007_remove_student_parents_delete_studentparent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='fee',
            name='currency_code',
            field=models.CharField(blank=True, help_text='Override school currency (e.g., KES, UGX, NGN). If null, uses school.currency_code', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='due_date_template',
            field=models.CharField(choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3'), ('monthly', 'Monthly'), ('custom', 'Custom Date')], default='term1', help_text='When this fee is typically due', max_length=20),
        ),
        migrations.AddField(
            model_name='fee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='amount_in_usd',
            field=models.FloatField(blank=True, help_text='Converted amount in USD for reporting (calculated via exchange rate)', null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='currency_code',
            field=models.CharField(default='USD', help_text='Currency code (KES, UGX, NGN, GHS, ZAR, TZS, ETB, USD, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete timestamp for audit trail', null=True),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('transfer', 'Bank Transfer'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('m_pesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('mtn_money', 'MTN Mobile Money'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['school', 'is_active'], name='finance_fee_school__0c97db_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['school', 'payment_date'], name='finance_pay_school__505f2f_idx'),
        ),
    ]
