# Generated by Django 5.2.12 on 2026-03-09 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0003_remove_student_photo_student_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='schools.school')),
                ('logo_url', models.URLField(blank=True, help_text='School logo URL', null=True)),
                ('primary_color', models.CharField(default='#003366', max_length=7)),
                ('secondary_color', models.CharField(default='#006699', max_length=7)),
                ('school_year', models.CharField(default='2024-2025', max_length=10)),
                ('attendance_threshold', models.IntegerField(default=75)),
                ('performance_threshold', models.FloatField(default=70.0)),
                ('enable_parent_portal', models.BooleanField(default=True)),
                ('enable_student_portal', models.BooleanField(default=True)),
                ('enable_teacher_portal', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('enable_email_alerts', models.BooleanField(default=True)),
                ('enable_sms_alerts', models.BooleanField(default=False)),
                ('default_fee_structure', models.JSONField(default=list, help_text="Default fee items: [{'name': 'Tuition', 'amount': 5000}, ...]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, help_text='Optional: if message is about a specific student', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAIInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_risk', models.FloatField(default=0.0)),
                ('performance_risk', models.FloatField(default=0.0)),
                ('low_attendance', models.BooleanField(default=False)),
                ('low_performance', models.BooleanField(default=False)),
                ('flagged_subjects', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='students.student')),
            ],
            options={
                'ordering': ['-performance_risk'],
            },
        ),
        migrations.CreateModel(
            name='RoleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'School Admin'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student'), ('bursar', 'Bursar')], max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, help_text='NULL for superadmin global settings', null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'ordering': ['role', 'key'],
                'unique_together': {('role', 'school', 'key')},
            },
        ),
    ]
