# Generated by Django 5.2.12 on 2026-03-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentaiinsights',
            options={'ordering': ['-overall_risk']},
        ),
        migrations.AddField(
            model_name='studentaiinsights',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentaiinsights',
            name='average_grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentaiinsights',
            name='days_absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentaiinsights',
            name='overall_risk',
            field=models.FloatField(default=0.0),
        ),
    ]
