# Generated by Django 5.2.12 on 2026-03-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the ministry', max_length=255)),
                ('state', models.CharField(help_text='State abbreviation or full name', max_length=100, unique=True)),
                ('contact_email', models.EmailField(help_text='Ministry contact email', max_length=254)),
                ('contact_phone', models.CharField(help_text='Ministry contact phone', max_length=20)),
                ('address', models.TextField(help_text='Ministry office address')),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ministries',
                'ordering': ['name'],
            },
        ),
    ]
