# Generated by Django 5.2.12 on 2026-03-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_subdomain_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='schools_sch_subdoma_88d5d3_idx',
            old_name='schools_sch_subdom_idx',
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='schools_sch_is_acti_522730_idx',
            old_name='schools_sch_is_act_idx',
        ),
        migrations.AddField(
            model_name='school',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='language',
            field=models.CharField(default='en', help_text='Default language for school', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='School logo image', null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#0066CC', help_text='Primary color in hex format', max_length=7),
        ),
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.CharField(blank=True, help_text='Geographic region for default templates', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('charter', 'Charter')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(default='#FF6600', help_text='Secondary color in hex format', max_length=7),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.CharField(default='UTC', help_text='e.g., Africa/Lagos, America/New_York', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='subdomain',
            field=models.CharField(help_text="Subdomain for accessing school (e.g., 'muse' for muse.altixedu.com)", max_length=100, unique=True),
        ),
    ]
