# Generated by Django 5.2.12 on 2026-04-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_ministry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['country', 'state_or_province'], 'verbose_name_plural': 'Ministries'},
        ),
        migrations.AlterField(
            model_name='ministry',
            name='country',
            field=models.CharField(help_text='Country (e.g., Nigeria, Kenya, Ghana, South Africa)', max_length=100),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='currency_code',
            field=models.CharField(default='NGN', help_text='ISO 4217 currency code (NGN for Nigeria, KES for Kenya, GHS for Ghana, etc.)', max_length=3),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='currency_symbol',
            field=models.CharField(default='₦', help_text='Currency symbol (₦ for Naira, KES for Kenyan Shilling, etc.)', max_length=5),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='name',
            field=models.CharField(help_text='Name of the ministry (e.g., Ministry of Education)', max_length=255),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='state_or_province',
            field=models.CharField(help_text='State/Province/Region name (e.g., Lagos, Nairobi, Accra)', max_length=100),
        ),
    ]
