# Generated by Django 5.2.12 on 2026-05-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_ministry_options_alter_ministry_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete timestamp (NULL = not deleted)', null=True),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['deleted_at'], name='schools_sch_deleted_94d691_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active', 'deleted_at'], name='schools_sch_is_acti_6683ae_idx'),
        ),
    ]
