# Generated by Django 5.2.12 on 2026-05-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_school_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='academic_year_format',
            field=models.CharField(choices=[('calendar', 'Calendar Year (Jan-Dec)'), ('african_sep', 'African Year (Sep-Aug)'), ('african_jan', 'Academic Year (Jan-Dec after sep-aug)'), ('custom', 'Custom Dates')], default='african_sep', help_text='School calendar format (most African schools: Sep-Aug)', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='currency_code',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code (KES, UGX, NGN, GHS, ZAR, TZS, ETB, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='school',
            name='currency_symbol',
            field=models.CharField(default='$', help_text='Currency symbol (e.g., ₦, KES, UGX)', max_length=10),
        ),
    ]
