# Generated by Django 5.2.12 on 2026-04-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0007_alter_ministry_options_alter_ministry_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('scale', 'Scale'), ('govt', 'Government')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_students', models.IntegerField()),
                ('max_teachers', models.IntegerField()),
                ('max_classrooms', models.IntegerField(default=100)),
                ('features', models.JSONField(default=dict)),
                ('support_level', models.CharField(choices=[('email', 'Email Only'), ('chat', 'Chat + Email'), ('phone', 'Priority Phone Support'), ('vip', 'VIP/Dedicated')], max_length=20)),
                ('trial_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Subscription Tiers',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='UpgradePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('promo_type', models.CharField(choices=[('launch', 'Launch Offer'), ('seasonal', 'Seasonal'), ('referral', 'Referral'), ('govt', 'Government Bulk')], max_length=50)),
                ('description', models.TextField()),
                ('discount_percentage', models.IntegerField()),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applicable_tiers', models.JSONField(default=list)),
                ('min_school_count', models.IntegerField(default=1)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='FreeSchoolPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students_count', models.IntegerField(default=0)),
                ('teachers_count', models.IntegerField(default=0)),
                ('daily_active_users', models.IntegerField(default=0)),
                ('features_used', models.JSONField(default=list)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('engagement_score', models.IntegerField(default=0)),
                ('is_ready_to_upgrade', models.BooleanField(default=False)),
                ('upgrade_trigger', models.CharField(blank=True, help_text="Why they should upgrade: 'storage_full', 'features_needed', etc", max_length=100)),
                ('upgrade_email_sent_count', models.IntegerField(default=0)),
                ('last_upgrade_email_sent', models.DateTimeField(blank=True, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_plan', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'Free School Plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annually')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_trial_converted', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('renewal_date', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('flutterwave_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('flutterwave_plan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('special_notes', models.TextField(blank=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='schools.school')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscriptiontier')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_method', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('bank_transfer', 'Bank Transfer'), ('manual', 'Manual (Invoice)')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('flutterwave_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.paymenttransaction')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='GovtSchoolTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='Ministry registration number', max_length=100)),
                ('ministry_approval_document', models.FileField(blank=True, help_text='PDF of ministry approval letter', null=True, upload_to='govt_approvals/')),
                ('approved_at', models.DateField()),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly (₦9,900)'), ('quarterly', 'Quarterly (₦29,700)'), ('annual', 'Annual (₦99,000)')], default='quarterly', max_length=20)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=9900, max_digits=10)),
                ('unlimited_students', models.BooleanField(default=True)),
                ('unlimited_teachers', models.BooleanField(default=True)),
                ('unlimited_classrooms', models.BooleanField(default=True)),
                ('priority_support', models.BooleanField(default=True)),
                ('is_bulk_purchase', models.BooleanField(default=False)),
                ('bulk_school_count', models.IntegerField(default=1)),
                ('bulk_discount_percentage', models.IntegerField(default=0)),
                ('tender_reference', models.CharField(blank=True, max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='govt_tier', to='schools.school')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.subscription')),
            ],
            options={
                'verbose_name_plural': 'Government School Tiers',
            },
        ),
        migrations.CreateModel(
            name='BillingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('trial_ending', 'Trial Ending Soon'), ('renewal_upcoming', 'Renewal Upcoming'), ('payment_failed', 'Payment Failed'), ('past_due', 'Payment Past Due'), ('upgrade_suggested', 'Upgrade Suggested')], max_length=50)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_alerts', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('attendance', 'Attendance Tracking'), ('grades', 'Grade Management'), ('fees', 'Fee Tracking'), ('messaging', 'Parent Messaging'), ('ai_alerts', 'AI Risk Alerts'), ('bulk_import', 'Bulk Import'), ('sms_alerts', 'SMS Alerts'), ('advanced_reports', 'Advanced Reports'), ('pdf_export', 'PDF Export'), ('api_access', 'API Access'), ('student_portal', 'Student Portal'), ('custom_integration', 'Custom Integration')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access', to='billing.subscriptiontier')),
            ],
            options={
                'verbose_name_plural': 'Feature Access',
                'unique_together': {('tier', 'feature')},
            },
        ),
    ]
