# Generated by Django 5.2.12 on 2026-04-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicyear_and_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'ordering': ['teacher', 'subject']},
        ),
    ]
