# Generated by Django 5.2.12 on 2026-05-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_classroom_options_alter_teachersubject_options'),
        ('schools', '0008_school_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'code'], name='academics_s_school__c27572_idx'),
        ),
    ]
