# Generated by Django 5.2.12 on 2026-05-05 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_subject_code_alter_subject_unique_together_and_more'),
        ('schools', '0009_school_academic_year_format_school_currency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3'), ('term4', 'Term 4'), ('semester1', 'Semester 1'), ('semester2', 'Semester 2'), ('quarter1', 'Quarter 1'), ('quarter2', 'Quarter 2'), ('quarter3', 'Quarter 3'), ('quarter4', 'Quarter 4')], help_text='Term identifier (Term 1, Semester 1, etc.)', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one term can be active per academic year')),
                ('school_reopens', models.DateField(blank=True, help_text='Date when school reopens after break', null=True)),
                ('school_closes', models.DateField(blank=True, help_text='Date when school closes for break', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['academic_year', 'start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['school', 'is_active'], name='academics_a_school__d90c4b_idx'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['academic_year', 'is_active'], name='academics_t_academi_99c025_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_year', 'name')},
        ),
    ]
