# Generated by Django 5.2.12 on 2026-04-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_payment_threshold_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentapprovalthreshold',
            options={'verbose_name_plural': 'Payment Approval Thresholds'},
        ),
        migrations.AlterField(
            model_name='paymentapprovalthreshold',
            name='country',
            field=models.CharField(help_text="Country (fetched from school's country)", max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentapprovalthreshold',
            name='currency_code',
            field=models.CharField(help_text='ISO 4217 currency code (NGN, KES, GHS, ZAR, etc.)', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentapprovalthreshold',
            name='tier1_amount',
            field=models.DecimalField(decimal_places=2, default=500000, help_text='Tier 1 threshold (e.g., 500,000 NGN in Nigeria, 5,000,000 KES in Kenya)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentapprovalthreshold',
            name='tier2_amount',
            field=models.DecimalField(decimal_places=2, default=2000000, help_text='Tier 2 threshold (e.g., 2,000,000 NGN in Nigeria, 20,000,000 KES in Kenya)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentapprovalthreshold',
            name='tier3_amount',
            field=models.DecimalField(decimal_places=2, default=5000000, help_text='Tier 3 threshold (e.g., 5,000,000 NGN in Nigeria, 50,000,000 KES in Kenya)', max_digits=15),
        ),
    ]
