# Generated by Django 5.2.12 on 2026-03-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_is_active_student_classroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Student photo URL', null=True),
        ),
    ]
