# Generated by Django 5.2.12 on 2026-04-28 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_ministry_options_alter_ministry_country_and_more'),
        ('students', '0005_health_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parent',
            name='parent_school_user_idx',
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(help_text='Unique per school', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['school'], name='students_pa_school__8efdc9_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['user'], name='students_pa_user_id_0748ea_idx'),
        ),
    ]
