# Generated by Django 5.2.12 on 2026-05-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_parent_parent_school_user_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parents',
        ),
        migrations.DeleteModel(
            name='StudentParent',
        ),
    ]
